Dapr WIP
edgefarm/anck pull request #4
Opened 2022-03-04 12:35 UTC by siredmar

2022-03-10 14:51 UTC, KairaMiu requested changes

2022-03-10 14:51 UTC, KairaMiu commented on controllers/network/jetstreams.go
> +func (j *Jetstream) Delete(names []string) error {
Rename of stream leads to a new jetstream, but the old one is never deleted:
- Create network `networkA` with jetstream `stream1`
- Jetstreams: `stream1`
- Update ressource network `networkA`: rename jetstream `stream1` to `stream2` and apply
- Jetstreams: `stream1`, `stream2`
- Delete ressource network `networkA`
- Jetstreams: `stream1`

2022-03-10 14:56 UTC, KairaMiu commented on config/manager/kustomization.yaml
> -  - name: controller
Fixed in review PR

2022-03-10 14:57 UTC, KairaMiu commented on config/samples/network_v1alpha1_network-account-only-sample.yaml
> -  usernames:
Fixed in review PR.

2022-03-10 15:09 UTC, KairaMiu commented on docs/images/dapr.puml
> +@startuml
Fixed in review PR

2022-03-10 15:09 UTC, KairaMiu commented on docs/images/global-streams.puml
> +folder "global_config" {
Fixed in review PR

2022-03-10 15:09 UTC, KairaMiu commented on devspace.yaml
> -dev:
Fixed in review PR

2022-03-11 10:17 UTC, KairaMiu requested changes

2022-03-11 10:17 UTC, KairaMiu commented on pkg/dapr/dapr.go
> +			Name:  "seedkey",
Shall be `seedKey`

2022-03-11 10:19 UTC, KairaMiu commented on pkg/dapr/dapr.go
> +			Name:  "seedkey",
Fixed in review PR

2022-03-11 14:09 UTC, KairaMiu requested changes
General: Secret entries are deleted, when participant is removed.  Secret itself is not deleted, when no participant left. Is this intended?

2022-03-11 14:10 UTC, KairaMiu commented on controllers/network/dapr.go
> +func removeParticipantFromDaprSecret(component, network, namespace string) error {
This is fixed in review PR.

2022-03-14 09:24 UTC, KairaMiu commented on controllers/network/dapr.go
> +func removeParticipantFromDaprSecret(component, network, namespace string) error {
Fixed in review PR.

2022-03-14 10:22 UTC, siredmar commented on main.go
> +	if err = (&networkcontrollers.ParticipantsReconciler{
this is an error

2022-03-14 11:01 UTC, siredmar commented on config/manager/kustomization.yaml
> -  - name: controller
cool!

2022-03-14 11:06 UTC, KairaMiu approved these changes

2022-03-16 13:15 UTC, merged